FROM node:14-buster

RUN apt-get update && apt-get install -y yarn build-essential vim less git 
#RUN apk --update add git vim less
#RUN git clone https://github.com/DashboardPack/architectui-react-theme-free /architectui-react-theme-free

#WORKDIR /architectui-react-theme-free

RUN npm install --global npm@latest
#RUN npm install --legacy-peer-deps 