all: compile setup

compile:
	node --unhandled-rejections=strict zkurrate/src/compile.js -i zkurrate/circuits/zkurrate.circom -o zkurrate/circuits/zkurrate.json -r

setup:
	mkdir -p zkurrate/setup && \
		node build/trustedsetup.js \
		-i zkurrate/circuits/zkurrate.json \
		-pk zkurrate/setup/zkurrate.pk.json \
		-vk zkurrate/setup/zkurrate.vk.json -r
